title: Ayush Kumar Singh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b> Enjoying life, one checkin at a time </b> 
  <br><br>
Experienced Software Engineer with demonstrated history of working for different R&D projects in different industry domains such as ITSM Portal for TCS, Server Management Portal for Cisco, Telecom Product for Amdocs using various frameworks and technologies in process such as Java, Spring MVC, HATEOAS REST Webservices, Fault tolerant Microservices, Springboot, KenanFX, Oracle/MySQL, Linux. 
  <br><br>
Strongly believe in continous learning. 
  <br><br>
Engoying my stint in Impetus working as Senior Software Engineer and learning BigData
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/7ayush7/">LinkedIn Connect</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
